<a href="https://colab.research.google.com/github/Yasir727/PythonLab/blob/YASIR-AHAMED-0264/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
a=np.array([1,3,0],float)
print(a)
print(a[-1])
print(a>2)

[1. 3. 0.]
0.0
[False  True False]


In [ ]:
import numpy as np
a=np.array([2,3,4])
print(type(a))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [ ]:
b=np.array((2,3,4))
print(type(b))

<class 'numpy.ndarray'>


In [ ]:

a=np.array([[1,2,5],[2,4,6]])
print(a[1][2])

6


In [ ]:
b=np.array([[1,2,3],[2,3,4],[2,4,5]])
print(a[0][1])

2


In [ ]:
arr=np.zeros((3,3),int)
print(arr)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [ ]:
arr=np.empty((3,4))

In [ ]:
arr=np.arange(10,30,5)
print(arr)

[10 15 20 25]


In [ ]:
arr=np.arange(0,2,0.3)
print(arr)

[0.  0.3 0.6 0.9 1.2 1.5 1.8]


In [ ]:
num=np.arange(0,100,2)
print("even numbers:",num)

even numbers: [ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94
 96 98]


In [ ]:
numb=np.arange(0,100,3)
print(numb)

[ 0  3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69
 72 75 78 81 84 87 90 93 96 99]


In [ ]:
import numpy as np
arr=np.linspace(0,2,9)
print(arr)

[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]


In [ ]:
help(np.linspace)

Help on function linspace in module numpy:

linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
    Return evenly spaced numbers over a specified interval.
    
    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].
    
    The endpoint of the interval can optionally be excluded.
    
    .. versionchanged:: 1.16.0
        Non-scalar `start` and `stop` are now supported.
    
    .. versionchanged:: 1.20.0
        Values are rounded towards ``-inf`` instead of ``0`` when an
        integer ``dtype`` is specified. The old behavior can
        still be obtained with ``np.linspace(start, stop, num).astype(int)``
    
    Parameters
    ----------
    start : array_like
        The starting value of the sequence.
    stop : array_like
        The end value of the sequence, unless `endpoint` is set to False.
        In that case, the sequence consists of all but the last of ``num + 1``
        evenly spaced samples, so that 

**Generating RANDOM Numbers in range 10 to 30 of 6 values**

In [ ]:
import numpy as np
x=np.random.randint(10,30,6)
print(x)

[22 17 13 29 10 26]


In [ ]:
!python --version


Python 3.10.12


In [ ]:
def quicksort(arr):
  if len(arr) <= 1:
    return arr
  pivot=arr[len(arr)//2]
  left =[x for x in arr if x < pivot]
  middle=[x for x in arr if x == pivot]
  right=[x for x in arr if x > pivot]
  return quicksort(left) + middle + quicksort(right)
print(quicksort([3,6,8,10,1,2,1]))

[1, 1, 2, 3, 6, 8, 10]


In [ ]:
lists=[3,6,8,10,1,2,1]
print(len(lists))

7


In [ ]:
def quicksort(arr):
  if len(arr) <= 1:
    return arr
  pivot=arr[len(arr)//2]
  left=[x for x in arr if x < pivot]
  middle=[x for x in arr if x == pivot]
  right=[x for x in arr if x > pivot]
  return quicksort(left) + middle + quicksort(right)
print(quicksort([10,2,4,0,1,2,3,2]))

[0, 1, 2, 2, 2, 3, 4, 10]
